/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionIdRouteImport } from './routes/section.$id'
import { Route as LessonIdRouteImport } from './routes/lesson.$id'
import { Route as CoursesProgrammingRouteImport } from './routes/courses.programming'
import { Route as CoursesPhonesRouteImport } from './routes/courses.phones'
import { Route as CoursesComputerRouteImport } from './routes/courses.computer'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionIdRoute = SectionIdRouteImport.update({
  id: '/section/$id',
  path: '/section/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonIdRoute = LessonIdRouteImport.update({
  id: '/lesson/$id',
  path: '/lesson/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesProgrammingRoute = CoursesProgrammingRouteImport.update({
  id: '/courses/programming',
  path: '/courses/programming',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesPhonesRoute = CoursesPhonesRouteImport.update({
  id: '/courses/phones',
  path: '/courses/phones',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesComputerRoute = CoursesComputerRouteImport.update({
  id: '/courses/computer',
  path: '/courses/computer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forum': typeof ForumRoute
  '/leaderboard': typeof LeaderboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/courses/computer': typeof CoursesComputerRoute
  '/courses/phones': typeof CoursesPhonesRoute
  '/courses/programming': typeof CoursesProgrammingRoute
  '/lesson/$id': typeof LessonIdRoute
  '/section/$id': typeof SectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forum': typeof ForumRoute
  '/leaderboard': typeof LeaderboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/courses/computer': typeof CoursesComputerRoute
  '/courses/phones': typeof CoursesPhonesRoute
  '/courses/programming': typeof CoursesProgrammingRoute
  '/lesson/$id': typeof LessonIdRoute
  '/section/$id': typeof SectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forum': typeof ForumRoute
  '/leaderboard': typeof LeaderboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/courses/computer': typeof CoursesComputerRoute
  '/courses/phones': typeof CoursesPhonesRoute
  '/courses/programming': typeof CoursesProgrammingRoute
  '/lesson/$id': typeof LessonIdRoute
  '/section/$id': typeof SectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/auth'
    | '/dashboard'
    | '/forum'
    | '/leaderboard'
    | '/notifications'
    | '/profile'
    | '/courses/computer'
    | '/courses/phones'
    | '/courses/programming'
    | '/lesson/$id'
    | '/section/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/auth'
    | '/dashboard'
    | '/forum'
    | '/leaderboard'
    | '/notifications'
    | '/profile'
    | '/courses/computer'
    | '/courses/phones'
    | '/courses/programming'
    | '/lesson/$id'
    | '/section/$id'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/auth'
    | '/dashboard'
    | '/forum'
    | '/leaderboard'
    | '/notifications'
    | '/profile'
    | '/courses/computer'
    | '/courses/phones'
    | '/courses/programming'
    | '/lesson/$id'
    | '/section/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ForumRoute: typeof ForumRoute
  LeaderboardRoute: typeof LeaderboardRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  CoursesComputerRoute: typeof CoursesComputerRoute
  CoursesPhonesRoute: typeof CoursesPhonesRoute
  CoursesProgrammingRoute: typeof CoursesProgrammingRoute
  LessonIdRoute: typeof LessonIdRoute
  SectionIdRoute: typeof SectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section/$id': {
      id: '/section/$id'
      path: '/section/$id'
      fullPath: '/section/$id'
      preLoaderRoute: typeof SectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$id': {
      id: '/lesson/$id'
      path: '/lesson/$id'
      fullPath: '/lesson/$id'
      preLoaderRoute: typeof LessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/programming': {
      id: '/courses/programming'
      path: '/courses/programming'
      fullPath: '/courses/programming'
      preLoaderRoute: typeof CoursesProgrammingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/phones': {
      id: '/courses/phones'
      path: '/courses/phones'
      fullPath: '/courses/phones'
      preLoaderRoute: typeof CoursesPhonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/computer': {
      id: '/courses/computer'
      path: '/courses/computer'
      fullPath: '/courses/computer'
      preLoaderRoute: typeof CoursesComputerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ForumRoute: ForumRoute,
  LeaderboardRoute: LeaderboardRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  CoursesComputerRoute: CoursesComputerRoute,
  CoursesPhonesRoute: CoursesPhonesRoute,
  CoursesProgrammingRoute: CoursesProgrammingRoute,
  LessonIdRoute: LessonIdRoute,
  SectionIdRoute: SectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
